# Generated by Django 4.2 on 2023-04-21 15:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_alter_produto_tamanho'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='okokok',
        ),
    ]
