# Generated by Django 4.2 on 2023-04-21 15:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_rename_staff_okokok'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='okokok',
            new_name='Staff',
        ),
    ]
