# Generated by Django 4.2 on 2023-04-21 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_okokok_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='ultimo_nome',
            new_name='apelido',
        ),
        migrations.RenameField(
            model_name='utilizador',
            old_name='ultimo_nome',
            new_name='apelido',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='numero_telefone',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='numero_telefone',
        ),
        migrations.AddField(
            model_name='staff',
            name='numero_telemovel',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999999)]),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='numero_telemovel',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999999)]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='morada',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='staff',
            name='num_cartao_cidadao',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999999)]),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='morada',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='nif',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999999)]),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='num_cartao_cidadao',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999999)]),
        ),
    ]
