# Generated by Django 4.2 on 2023-04-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_produto_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='email',
            field=models.EmailField(default='defaultMail@gmail.com', max_length=150),
        ),
    ]
