# Generated by Django 4.2 on 2023-04-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_utilizador_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(default='defaulStaffMail@gmail.com', max_length=150),
        ),
    ]
