# Generated by Django 4.2 on 2023-04-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_staff_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='image',
            field=models.ImageField(default='whiteLogo.png', upload_to='images/'),
        ),
    ]
