# Generated by Django 4.2 on 2023-04-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_produto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='referencia',
            field=models.CharField(max_length=4),
        ),
    ]
