# Generated by Django 4.2 on 2023-05-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='referencia',
            field=models.CharField(default=None, max_length=4),
        ),
    ]
