# Generated by Django 4.2 on 2023-05-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_comentario_utilizador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='referencia',
        ),
        migrations.AddField(
            model_name='comentario',
            name='image',
            field=models.CharField(default='pescadaDraw.png', max_length=255),
        ),
    ]
