# Generated by Django 4.2 on 2023-05-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_comentario_referencia_comentario_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
