# Generated by Django 4.1.7 on 2023-05-05 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_carrinhocompras_utilizador_carrinhoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinhocompras',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.CreateModel(
            name='HistoricoCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_finalizada', models.DateTimeField(auto_now_add=True)),
                ('carrinho', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.carrinhocompras')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.utilizador')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('itens_comprados', models.ManyToManyField(to='store.carrinhoitem')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.utilizador')),
            ],
        ),
    ]
