# Generated by Django 4.1.7 on 2023-05-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_carrinhocompras_valor_total_historicocarrinho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='data_nascimento',
            field=models.DateField(auto_now_add=True),
        ),
    ]
