# Generated by Django 4.1.7 on 2023-05-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_comentario_data_alter_staff_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='data_nascimento',
            field=models.DateField(auto_now_add=True),
        ),
    ]
