# Generated by Django 4.1.7 on 2023-05-05 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_utilizador_data_nascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('data_finalizada', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.produto')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.utilizador')),
            ],
        ),
        migrations.DeleteModel(
            name='HistoricoCarrinho',
        ),
    ]
