# Generated by Django 4.1.7 on 2023-05-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_historico_delete_historicocarrinho'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Historico',
            new_name='Historico_item',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
